# Generated by Django 3.0.4 on 2020-03-31 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savour', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IceBowl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoop_number', models.PositiveIntegerField(default=40)),
                ('ice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ice_cream_app.Ice')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_command', models.CharField(max_length=50)),
                ('ask_scoop_number', models.IntegerField()),
                ('ice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ice_cream_app.Ice')),
            ],
        ),
    ]
